version: "3.9"
services:
   
    dcf:
        image: dcf-data-processing:1.1
        container_name: dcf
        hostname: dcf-domain
        ports:
          - "1028:1028"
        expose:
        - "1028"
    
networks:
    default:
        name: orionld_default
        external: true