version: "3.9"
services:
   
    dcf:
        image: docker.ramp.eu/tau-pvt/dcf:1.9.6
        container_name: dcf
        hostname: dcf
        ports:
          - "1028:1028"
        expose:
        - "1028"
    mongo-db:
        image: mongo:3.6
        hostname: mongo-db-dcf
        container_name: db-mongo-dcf
        ports:
          - "27018:27017" 
        networks:
          - default
        command: --nojournal
        volumes:
          - mongo-db-dcf:/data

volumes:
  mongo-db-dcf: ~